name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, "3.10", "3.11"]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Print Python information
        run: python --version
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Verify code format with black
        run: |
          pip install black
          black . --check
        if: matrix.python-version != '2.7' && matrix.python-version != '3.5'
      - name: Run unit tests
        run: python setup.py test
